# Default values for cluster-machine-approver.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

provider:
  type: YandexCloud
  name: yandex

replicaCount: 1

nodeSelector:
  node-role.kubernetes.io/control-plane: ""

image:
  repository: dobrykot/cluster-machine-approver
  tag: ""
  pullPolicy: IfNotPresent

terminationMessagePath:
terminationMessagePolicy:
resources:  {}
securityContext: {}
env: []
tolerations: []

defaults:
  resources:
    limits:
      cpu: 200m
      memory: 200Mi
    requests:
      cpu: 100m
      memory: 100Mi
  env:
    - name: YANDEX_AIM_JSON
      valueFrom:
        secretKeyRef:
          name: yandex-cloud
          key: serviceAccountJSON
    - name: YANDEX_FOLDER_ID
      valueFrom:
        secretKeyRef:
          name: yandex-cloud
          key: folderID
    - name: INSTANCE_NAME_LAYOUT
      value: '^\w*:\w*:(.*)'
    - name: KubeHost
      value: "kubernetes.default"
  securityContext: {}
  tolerations:
  - key: "node.cloudprovider.kubernetes.io/uninitialized"
    value: "true"
    effect: "NoSchedule"
  - key: "node-role.kubernetes.io/control-plane"
    effect: "NoSchedule"
  - key: "node-role.kubernetes.io/master"
    effect: "NoSchedule"
  - key: "CriticalAddonsOnly"
    operator: "Exists"
  terminationMessagePath: /dev/termination-log
  terminationMessagePolicy: File
