{{- with .Values.appSpec.applications.operator }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    rbac.authorization.k8s.io/aggregate-to-cluster-reader: "true"
  name: {{ $.Release.Name }}-{{ .name }}
rules:
  - apiGroups:
    - machineconfiguration.openshift.io
    resources:
    - containerruntimeconfigs
    - controllerconfigs
    - kubeletconfigs
    - machineconfigpools
    verbs:
    - get
    - list
    - watch
  - apiGroups:
    - config.openshift.io
    resources:
    - infrastructures
    verbs:
    - get
    - list
    - watch
  - apiGroups:
    - ""
    resources:
    - configmaps
    verbs:
    - get
    - list
    - watch
{{- end }}
