apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.provider.name }}-{{ include "cluster-machine-approver.name" . }}
  labels:
    {{- include "cluster-machine-approver.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "cluster-machine-approver.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "cluster-machine-approver.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "cluster-machine-approver.name" . }}
      containers:
        - name: {{ include "cluster-machine-approver.name" . }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          {{- with .Values.resources | default .Values.defaults.resources }}
          resources:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.securityContext | default .Values.defaults.securityContext }}
          securityContext:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.env | default .Values.defaults.env }}
          env:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          terminationMessagePath: {{ .Values.terminationMessagePath | default .Values.defaults.terminationMessagePath }}
          terminationMessagePolicy: {{ .Values.terminationMessagePolicy | default .Values.defaults.terminationMessagePolicy }}
      {{- with .Values.tolerations | default .Values.defaults.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
